### ISSUE TITLE
webpack: Failed to compile

### ISSUE THREAD

**Issue by cdiaz** [nvx-sum/sum-app#7]
/src/app/root/root.component.ts (21,26): Argument of type '{ grid: { v: number; h: number; }; colors: { body: { color: string; text: string; }; brand: { col...' is not assignable to parameter of type 'KitDefaultThemeParams'.
  Types of property 'shadows' are incompatible.
    Type '{ element: string; deep: string; }' is not assignable to type '{ element: string; deep: string; overlay: string; }'.
      Property 'overlay' is missing in type '{ element: string; deep: string; }'.

**Steps to reproduce:**
`npm start`

**Environment:**
npm 4.2.0
angular/cli: 1.1.3
node: 7.9.0
os: linux x64

**Comment by Navix** [comment]
Thanks for the issue. I will fix it shortly.
